title: Divij Bindlish
email: me@divijbindlish.in
permalink: /blog/:title
description: Blog of Divij Bindlish - Developer at SDSLabs, tech enthusiast, student at IIT Roorkee.
baseurl: ""
url: "https://divijbindlish.in"
twitter_username: divijbindlish
github_username:  divijbindlish

# Build settings
markdown: kramdown
